apiVersion: v1
kind: Service
metadata:
    name: "onlinejudge-5388"
    labels:
        app: "onlinejudge-5388"
spec:
    type: LoadBalancer
    ports:
    - port: 443
      targetPort: 443
      protocol: TCP
      name: http
    selector:
        app: "onlinejudge-5388"